### ISSUE TITLE
Incorrect attribution for NSData+Base64.h/.m

### ISSUE THREAD

**Issue by superwills** [StCredZero/SCZ-BasicEncodingRules-iOS#1]
This is Matt Gallagher's code

http://www.cocoawithlove.com/2009/06/base64-encoding-options-on-mac-and.html

Use the correct attribution for that header and .m.

It is also already in github, but with the correct attribution
https://github.com/l4u/NSData-Base64

**Comment by StCredZero** [comment]
Thanks! I will change this in a bit.

On Thu, Apr 18, 2013 at 6:53 PM, superwills notifications@github.comwrote:

> This is Matt Gallagher's code
> 
> http://www.cocoawithlove.com/2009/06/base64-encoding-options-on-mac-and.html
> 
> Use the correct attribution for that header and .m.
> 
> It is also already in github, but with the correct attribution
> https://github.com/l4u/NSData-Base64
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/StCredZero/SCZ-BasicEncodingRules-iOS/issues/1
> .

## 

There's neither heaven nor hell,
save what we grant ourselves.
There's neither fairness nor justice,
save what we grant each other.

**Comment by StCredZero** [comment]
I just looked at this code. It's not the same code. (Compare the two
implementations of: - (NSString *)base64EncodedString)

How are you sure that this is not a legit reimplementation of a
NSData+Base64 category?

On Thu, Apr 18, 2013 at 6:53 PM, superwills notifications@github.comwrote:

> This is Matt Gallagher's code
> 
> http://www.cocoawithlove.com/2009/06/base64-encoding-options-on-mac-and.html
> 
> Use the correct attribution for that header and .m.
> 
> It is also already in github, but with the correct attribution
> https://github.com/l4u/NSData-Base64
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/StCredZero/SCZ-BasicEncodingRules-iOS/issues/1
> .

## 

There's neither heaven nor hell,
save what we grant ourselves.
There's neither fairness nor justice,
save what we grant each other.

**Comment by superwills** [comment]
Fair enough.  It is quite different on closer inspection.

**Comment by StCredZero** [comment]
Natural mistake. Thanks for doing the right thing and bringing it to my attention.
