### ISSUE TITLE
Incorrect SecKeyRef object obtained 

### ISSUE THREAD

**Issue by Daemon-Devarshi** [StCredZero/SCZ-BasicEncodingRules-iOS#3]
I am trying to generate SecKeyRef object from modulus and exponent. Below is the part of code which I used:
- (void)viewDidLoad
  {
  [super viewDidLoad];
  // Do any additional setup after loading the view, typically from a nib.
  
  [[SecKeyWrapper sharedWrapper] removePeerPublicKey:kPeerName];
  [self storeGeneratedPublicKeyDataFromModulus:@"b362270499507a161edfe839de79e585eb43564119eb5920b144414a22a70f708064c8ea3b22df3ece799825da78cadb7175e22a4896da77df2a854326a75a5ed0476ada51ab9a92c86c9845a5495dc2977db94e0ad6d16861400cd33e4260300db97b82c5ce7906e65c6b8e2419411d9549dcb5b473a8ef01651af49d2d17223911336ca51d04bfd01646bbe0c2e1cb68f03bca5afd283c3ae9637a9c676bd93811bcebbc3ea05cdccec12b043d8bd613e37456f5012e6bc5cbb73f3a09c680768ba94f883b056c54137569e7c047abc0e478ac3a5fd65d58071ee0e03e43811aa400717b8558ff26804050d4fab3defd694cdba647a1e2a069de17150db331" exponent:10001];
  }
- (void)storeGeneratedPublicKeyDataFromModulus:(NSString *)modulus exponent:(int)exponent
  {
  // generate public key as NSData object
  NSData *pubKeyModData = [[NSData alloc] initWithBase64EncodedString:modulus options:NSDataBase64DecodingIgnoreUnknownCharacters];
  // NSData *pubKeyExpData = [exponent dataUsingEncoding:NSUTF8StringEncoding];
  
  NSData *pubKeyExpData = [NSData dataWithBytes: &exponent length: sizeof(exponent)];
  
  NSMutableArray *testArray = [[NSMutableArray alloc] init];
  [testArray addObject:pubKeyModData];
  [testArray addObject:pubKeyExpData];
  NSData *testPubKey = [testArray berData];
  
  // store in keychain
  SecKeyWrapper *secKeyWrapper = [SecKeyWrapper sharedWrapper];
  SecKeyRef publicKeyRef = [secKeyWrapper addPeerPublicKey:kPeerName keyBits:testPubKey]; // when we log this it shows different modulus and exponent
  }

The publicKeyRef object returned in above method when logged shows different modulus and exponent components than the one which we passed.

Any ideas?

**Comment by StCredZero** [comment]
I don't think the arguments mean what you think they do. Please look at the method doc, and this has nothing directly to do with my library,
